[build]
  publish = "public"
  command = "npm run build"
  functions="lambda"
[dev]
  publish = "src"
  command = "yarn dev"
  functions="lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
